
language: python

python:
  - "3.6.8"

# Comando para instalar dependencias
install:
  - pip install invoke
  - invoke build
  #- pip install -r requirements.txt

# Comando para ejecutar los test
script:
  - invoke test
  - invoke codecov
