
language: python

python:
  - "3.6.8"
  - "3.6"

# Comando para instalar dependencias
install:
  - pip install -r requirements.txt

# Comando para ejecutar los test
script:
  - invoke test
