
language: python

# Versiones del lenguaje
python:
  - "3.6.8"
  - "3.7"

# Comando para instalar dependencias
install:
  - pip install invoke
  - invoke install

# Comando para ejecutar los test
script:
  - invoke test
  - invoke codecov
